package edu.mit.gamedap.generator;

import java.util.List;

/**
 * Represents a cluster of vectors generated by the competitive learning algorithm.
 */
public class VectorCluster<T> {
  private final List<Vector<T>> vectors;
  private final Vector<T> center;

  public VectorCluster (Vector<T> center, List<Vector<T>> vectors) {
    this.center = center;
    this.vectors = vectors;
  }

  // TODO: methods to get center and vectors, something to find distance between center & vectors
}
