package edu.mit.gamedap.generator.datatypes;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a cluster of vectors generated by the competitive learning algorithm.
 */
public class VectorCluster<T> {
  private final List<Vector<T>> vectors;
  private final Vector<T> center;

  public VectorCluster (Vector<T> center, List<Vector<T>> vectors) {
    this.center = center;
    this.vectors = vectors;
  }

  public Vector<T> getCenter() {
    return this.center;
  }

  public List<Vector<T>> getVectors() {
    return new ArrayList<>(this.vectors);
  }

  public String info() {
    String vectorString = "[";
    for (Vector<T> v : vectors) {
      vectorString += v.toString() + "  ";
    }
    vectorString += "]";
    return String.format("<VectorCluster: center=%s, vectors=%s", this.center.toString(), vectorString);
  }
}
